local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()

local Window = OrionLib:MakeWindow({Name = "WhyHub", HidePremium = false,IntroText = "WhyHub" , SaveConfig = true, ConfigFolder = "OrionTest"})

local Tab = Window:MakeTab({Name = "Auto Farm",Icon = "rbxassetid://4483345998",PremiumOnly = false})



local Section = Tab:AddSection({
	Name = "Rifle AutoFarm"
})

Tab:AddButton({
	Name = "Fishman Insta TP",
	Callback = function()
	     local teleport_table = {
    location25 = Vector3.new(5639, -94, -16612) -- your desired position
}

local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(0,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location25)
      		print("button pressed")
  	end    
})

Tab:AddButton({
	Name = "Rifle Farm set pos",
	Callback = function()
	     local teleport_table = {
    location26 = Vector3.new(7487, -2149, -17320) -- your desired position
}

local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(40,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location26)
      		print("button pressed")
  	end    
})

Tab:AddButton({
	Name = "Rifle AutoFarm",
	Callback = function()
while wait() do

local args = {
    [1] = "fire",
    [2] = {
        ["Start"] = CFrame.new(7489.91796875, -2148.17236328125, -17320.529296875) * CFrame.Angles(1.4612444639205933, -0.06177064776420593, 1.164029836654663),
        ["Gun"] = "Rifle",
        ["joe"] = "true",
        ["Position"] = Vector3.new(7669.64404296875, -2176.386474609375, -17323.162109375)
    }
}

game:GetService("ReplicatedStorage").Events.CIcklcon:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "reload",
    [2] = {
        ["Gun"] = "Rifle"
    }
}

game:GetService("ReplicatedStorage").Events.CIcklcon.gunFunctions:InvokeServer(unpack(args))

end
	    
      		print("button pressed")
  	end    
})


local Tab = Window:MakeTab({Name = "Islands TP",Icon = "rbxassetid://4483345998",PremiumOnly = false})

OrionLib:MakeNotification({	Name = "Succefull!",Content = "Injected",Image = "rbxassetid://4483345998",Time = 4})

Tab:AddLabel("Choose Island")

local Section = Tab:AddSection({
	Name = "ISLANDS"
})

Tab:AddButton({
	Name = "Town of Beginners",
	Callback = function()
	     local teleport_table = {
    location1 = Vector3.new(929.904785, 9.00013733, 954.264587, 0.999959707, 0, 0.00897739921, 0, 1, 0, -0.00897739921, 0, 0.999959707) -- your desired position
}

local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(100,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location1)
      		print("button pressed")
  	end    
})

Tab:AddButton({
	Name = "Sandora",
	Callback = function()
	     local teleport_table = {
    location2 = Vector3.new(-1180.88635, 2.15429783, 1108.64404, -0.0443007946, 0, 0.999018192, 0, 1, 0, -0.999018192, 0, -0.0443007946) -- your desired position
}

local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(100,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location2)
      		print("button pressed")
	end    
})
Tab:AddButton({
    Name = "Shell Town",
	Callback = function()
	    local teleport_table = {
    location3 = Vector3.new(-478, 6, -4356)
}
local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(125,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location3)
      		print("button pressed")
  	end    
})

Tab:AddButton({
	Name = "Zou Island",
	Callback = function()
	    local teleport_table = {
    location4 = Vector3.new(-4307, 7, -2566)
}
local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(125,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location4)
      		print("button pressed")
  	end    
})

Tab:AddButton({
	Name = "Restaurant Baratie",
	Callback = function()
	    local teleport_table = {
    location5 = Vector3.new(-3908, 6, -5723)
}
local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(167,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location5)
      		print("button pressed")
  	end    
})

Tab:AddButton({
	Name = "Shark Park",
	Callback = function()
	    local teleport_table = {
    location6 = Vector3.new(878, 4, -13150)
}
local tween_s = game:GetService('TweenService')
local tweeninfo = TweenInfo.new(325,Enum.EasingStyle.Linear)

local lp = game.Players.LocalPlayer

function bypass_teleport(v)
    if lp.Character and 
    lp.Character:FindFirstChild('HumanoidRootPart') then
        local cf = CFrame.new(v)
        local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
        a:Play()
    end
end

bypass_teleport(teleport_table.location6)
      		print("button pressed")
  	end    
})

local Tab = Window:MakeTab({Name = "Player",Icon = "rbxassetid://4483345998",PremiumOnly = false})

local Section = Tab:AddSection({
	Name = "Player"
})

Tab:AddButton({
	Name = "ESP",
	Callback = function()
      		print("button pressed")
      		
      		while wait(1) do
local Players = game:GetService("Players"):GetChildren()
local Hightlight = Instance.new("Highlight")
Hightlight.Name = "Hightlight"
Hightlight.OutlineColor = Color3.new(1, 0, 0.0156863)

for i, v in pairs(Players) do
	repeat wait() until v.Character
	local HightlightClone = Hightlight:Clone()
	HightlightClone.Adornee = v.Character
	HightlightClone.Parent = v.Character:FindFirstChild("HumanoidRootPart")
end



game.Players.PlayerAdded:Connect(function(player)
	repeat wait() until Players.Character 
	local hightlightClone = Hightlight:Clone()
	hightlightClone = Players.CharacterAutoLoads
	hightlightClone.Adornee = Players.Character
	hightlightClone.Parent = Players.Character:FindFirstChild("HumanoidRootPart")
end)
end
  	end    
})

Tab:AddButton({
	Name = "GOD MODE | Toggle all function (esp) ",
	Callback = function()
	    local Player = game.Players.LocalPlayer
	    local Character = Player.Character or Player.CharacterAdded:wait()
	    local Hrp = Player.Character:FindFirstChild("HumanoidRootPart")
	    Hrp:Destroy()
 end
})

Tab:AddToggle({
	Name = "WalkSpeed EU",
	Default = false,
	Save = true,
	Callback = function(Value)
		print(Value)

		  getgenv().WalkSpeed = Value
            while WalkSpeed == true do
                game:GetService("RunService").Stepped:wait() 
                game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame + game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame.lookVector * 1
                wait()
                end
	end    
})

Tab:AddToggle({
	Name = "WalkSpeed USA/Asia",
	Default = false,
	Save = true,
	Callback = function(Value)
		print(Value)
		  getgenv().WalkSpeed = Value
            while WalkSpeed == true do
                game:GetService("RunService").Stepped:wait() 
                game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame + game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame.lookVector * 3
                wait()
                end
	end    
})

Tab:AddButton({
	Name = "Inf Jumps",
	Callback = function()
      		print("button pressed")
      		local Player = game.Players.LocalPlayer

local char = Player.Character or Player.CharacterAdded:wait()
local hum = char:WaitForChild("Humanoid")
 
local uis = game:GetService("UserInputService")
 
local jumps = 0
local maxJumps = 9999999
 
local currentTick = tick()
 
hum.StateChanged:Connect(function(oldState, newState)
    if newState == Enum.HumanoidStateType.Landed then
        jumps = 0
    end
end)
 
uis.JumpRequest:Connect(function()
    if jumps < maxJumps and tick() - currentTick > 0.2 then
       jumps += 1
        currentTick = tick()
        hum:ChangeState(Enum.HumanoidStateType.Jumping)
    end
end)
  	end    
})

Tab:AddButton({
	Name = "NO FALL DMG",
	Callback = function()
      		print("button pressed")
      		
game:GetService("ReplicatedStorage").Events.FALLDmg:Destroy()

    end    
})

local Tab = Window:MakeTab({
	Name = "Misc",
	Icon = "rbxassetid://4483345998",
	PremiumOnly = false
})

local Section = Tab:AddSection({
	Name = "Misc"
})

Tab:AddButton({
	Name = "ChatLogger",
	Callback = function()
      		print("button pressed")
      		loadstring(game:HttpGet("https://pastebin.com/raw/stggPUBM", true))()
  	end    
})
